name: gmail_clone
description: "A project to clone the UI of Gmail app using Flutter"
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: 
  flutter_launcher_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "assets/icon/ic_launcher_adaptive_back.png"